### ISSUE TITLE
myPortfolio

### ISSUE THREAD

**Issue by Aleksis99999** [Aleksis99999/Portfolio#1]
![Portfolio-1](https://user-images.githubusercontent.com/130615436/232420382-9af44d19-12ae-4d59-ac8f-24a6934ef4bd.jpg)

**Comment by notMONGCHAW** [comment]
Do you still need help regarding something?

**Comment by Aleksis99999** [comment]
sorry, I have already finished it. Thank you for your reply.

**Comment by notMONGCHAW** [comment]
Close it dude
